### ISSUE TITLE
官网修复401后的新bug

### ISSUE THREAD

**Issue by strongrex2001** [strongrex2001/TunerTodoList#8]
Review现在点不了second comment
```plain
TypeError: "t.user is undefined"
```
+ 为什么我F12能看到Vue的源码，是不是你开了debug mode？
跟着你的源码我顺路发现review里面下载谱面文件等等一票功能全都炸了，共同点是访问了`this.user`。

我猜想可能漏了一个data字段或者应该是`this.$user`。

**Comment by Darkmota** [comment]
Vue组件中增加computed data时发生了duplicate key，导致之前使用了全局state和review信息的computed data被后面的computed{}覆盖。

**Comment by Darkmota** [comment]
已修复

**Comment by strongrex2001** [comment]
不行，等上线了我再Close

**Comment by Darkmota** [comment]
我上线了才comment的。

**Comment by strongrex2001** [comment]
Verified.
